sonar.projectKey=multicloudx
sonar.projectName=MultiCloudX
sonar.sources=applications
sonar.tests=applications
sonar.exclusions=**/target/**,**/*.tfstate*,**/.terraform/**
sonar.java.binaries=applications/**/target/classes
